proManage/proManage/properties/urls.py
from django.conf.urls import patterns, url
from proManage.properties import views
from .views import *

urlpatterns = patterns('',
     url(r'^$', 'django.contrib.auth.views.login',{'template_name': 'properties/login.html'} , name='login'),
     url(r'^landing$', views.landing, name='landing'),
     url(r'^user_list$', views.user_list, name='user_list'),
     url(r'^property_list$', views.property_list, name='property_list'),
     url(r'^report_list$', views.report_list, name='report_list'),
     url(r'^report_new$', views.report_create, name='report_new'),
     url(r'^report_delete/(?P<pk>\d+)$', views.report_delete, name='report_delete'),
     url(r'^new$', views.user_create, name='user_new'),
     url(r'^property_new$', views.property_create, name='property_new'),
     url(r'^add_manager/(?P<pk>\d+)$', views.add_manager, name='add_manager'),
     url(r'^add_tenant/(?P<pk>\d+)$', views.add_tenant, name='add_tenant'),
     url(r'^unit_add/(?P<pk>\d+)$', views.unit_create, name='unit_add'),
     url(r'^edit/(?P<pk>\d+)$', views.user_update, name='user_edit'),
     url(r'^logout$', views.logout_view, name='logout'),
     url(r'^sorry$', views.sorry, name='sorry'),
     url(r'^property_edit/(?P<pk>\d+)$', views.property_update, name='property_edit'),
     url(r'^remove_manager/(?P<pk>\d+)/(?P<mgr>\d+)$', views.remove_manager, name='remove_manager'),
     url(r'^remove_tenant/(?P<pk>\d+)/(?P<ten>\d+)$', views.remove_tenant, name='remove_tenant'),
     url(r'^unit_edit/(?P<pk>\d+)$', views.unit_update, name='unit_edit'),
     url(r'^delete/(?P<pk>\d+)$', views.user_delete, name='user_delete'),
     url(r'^delete/(?P<pk>)$', views.no_delete, name='user_delete'),
     url(r'^property_delete/(?P<pk>\d+)$', views.property_delete, name='property_delete'),
     url(r'^property_delete/(?P<pk>\d+)$', views.property_no_delete, name='property_delete'),
     url(r'^unit_delete/(?P<pk>\d+)$', views.unit_delete, name='unit_delete'),
     url(r'^unit_delete/(?P<pk>\d+)$', views.unit_no_delete, name='unit_delete'),
     url(r'^unit_view_info/(?P<pk>\d+)$', views.unit_view_info, name='unit_view_info'),
     url(r'^workorder_list$', views.workorder_list, name='workorder_list'),
     url(r'^workorder_new$', views.workorder_create, name='workorder_new'),
     url(r'^workorder_edit/(?P<pk>\d+)$', views.workorder_update, name='workorder_edit'),
     url(r'^sms_me$', views.sms_me, name='sms_me'),
)

proManage/proManage/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('proManage.properties.urls', namespace="properties"))
)

proManage/proManage/properties/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.contrib.postgres.fields import ArrayField

class Property(models.Model):
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=30)
    state = models.CharField(max_length=2)
    zipcode = models.CharField(max_length=5)
    name = models.CharField(max_length=30, null=True)

    def __str__(self):
        return self.name

class Unit(models.Model):
    building = models.ForeignKey(Property)
    size = models.IntegerField(default=0)
    aptType = models.CharField(max_length=20, default="Apartment")
    rentalFee = models.IntegerField(default=0)
    unitNumber = models.CharField(max_length=5, default="1")

    def __str__(self):
        return str(self.building) + ' (Unit ' + str(self.unitNumber) + ')'

class TenantInfo(models.Model):
    user = models.ForeignKey(User)
    ssn = models.CharField(max_length=12)
    phone = models.CharField(max_length=20)

    def __str__(self):
        return self.user

class UnitGroup(models.Model):
    users = ArrayField(models.IntegerField(default=0), blank=True, default=list)
    unit = models.ForeignKey(Unit)

    def __str__(self):
        return str(self.unit.building) + ' ' + str(self.unit)

class WorkOrder(models.Model):
    createdBy = models.ForeignKey(User)
    unit = models.ForeignKey(Unit)
    postedDate = models.DateTimeField(auto_now_add=True)
    lastUpdated = models.DateTimeField(True)
    problem = models.CharField(max_length=2000)
    cost = models.FloatField(null=True)
    access = models.BooleanField()
    status = models.NullBooleanField()

    def __str__(self):
        return self.unit + ' (' + self.postedDate + ')'

class PropertyGroup(models.Model):
    users = ArrayField(models.IntegerField(default=0), blank=True, default=list)
    prop = models.ForeignKey(Property)

    def __str__(self):
        return str(self.prop)

class Report(models.Model):
     filename = models.CharField(max_length=50)
     fileDescription = models.CharField(max_length=100)
     fileBytes = models.FileField()
    

proManage/proManage/properties/views.py
from django.core.urlresolvers import reverse 
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm
from .models import Property, Unit, Report, TenantInfo, UnitGroup, User, Group, WorkOrder, PropertyGroup
from django import forms
from django.contrib.auth.decorators import permission_required
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm 
from twilio.rest import TwilioRestClient
import datetime

### Forms ### 

class UserForm(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'first_name', 'last_name']

class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'groups']

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.save()
        user.groups = self.cleaned_data["groups"]
        if commit:
           user.save()
        return user

class TenantInfoForm(ModelForm):
    class Meta:
        model = TenantInfo
        fields = ['ssn','phone']

class WorkOrderForm(ModelForm):
    access = forms.BooleanField(widget=forms.CheckboxInput())
    problem = forms.CharField(widget=forms.Textarea(attrs={'rows':5, 'cols':40}))
    cost = forms.FloatField(widget=forms.NumberInput(attrs={'step':0.01}))
    class Meta:
        model = WorkOrder
        fields = ['unit', 'problem', 'cost', 'status','access']

class PropertyForm(ModelForm):
    class Meta:
        model = Property
        fields = ['address', 'city', 'state', 'zipcode', 'name']

class UnitForm(ModelForm):
    rentalFee = forms.FloatField(widget=forms.NumberInput(attrs={'step':0.01}))
    class Meta:
        model = Unit
        fields = ['size', 'aptType', 'rentalFee', 'unitNumber']

        
class AddManagerForm(forms.Form):
    users = User.objects.filter(groups__name='Managers')
    manager = forms.ModelChoiceField(users)

class AddTenantForm(forms.Form):
    users = User.objects.filter(groups__name='Tenants')
    tenant = forms.ModelChoiceField(users)
    
class ReportForm(ModelForm):
    fileBytes = forms.FileField()
    class Meta:
        model = Report
        fields = ['fileBytes', 'fileDescription']

class TextForm(forms.Form):
    textdata = forms.CharField(widget=forms.Textarea)

    def isValid(self):
        if self.data.get('textdata'):
            print 'im valid'
            return True


### Authorization Helper Functions ###

def handle_uploaded_file(file_path):
    print "handle_uploaded_file"
    dest = open(file_path.name,"wb")
    for chunk in file_path.chunks():
        dest.write(chunk)
    dest.close()

def sorry(request, template_name='properties/sorry.html'):
    return render(request, template_name)

def check_authorization(user, user_group):
    return (user.id in user_group)





### User CRUD Functions ###

def user_list(request, template_name='properties/user_list.html'):
    if not request.user.is_authenticated():
        return redirect("/")
    if request.user.is_superuser:
        users = User.objects.all()
    elif request.user in User.objects.filter(groups__name='Managers'):
        user_ids = []
        for prop_group in PropertyGroup.objects.all():
            if request.user.id in prop_group.users:
                user_ids.extend(prop_group.users)
        user_ids = list(set(user_ids))
        users = User.objects.filter(id__in=user_ids)
    else:
        users = User.objects.filter(username=request.user.username)
    data = {}
    data['object_list'] = users
    return render(request, template_name, data)
    
def landing(request, template_name='properties/landing.html'):
    if not request.user.is_authenticated():
        return redirect("/")
    data = {}
    return render(request, template_name, data)

def user_create(request, template_name='properties/user_form.html'):
    if not request.user.is_authenticated():
        return redirect("/")
    if not request.user.is_superuser:
        return redirect('properties:sorry')
    userForm = UserCreateForm(request.POST or None)
    infoForm = TenantInfoForm(request.POST or None)
    if userForm.is_valid() and infoForm.is_valid():
        user = userForm.save()
        info = infoForm.save(commit=False)
        print 'here is the user:',
        print user
        info.user = user
        info.save()
        return redirect('properties:user_list')
    return render(request, template_name, {'userForm':userForm, 'infoForm': infoForm, 'isNew':True})

def user_update(request, pk, template_name='properties/user_form.html'):
    if not request.user.is_authenticated():
        return redirect("/")
    user = get_object_or_404(User, pk=pk)
    #info = TenantInfo.objects.get(user=user)
    if not request.user.id == user.id and not request.user.is_superuser:
        return redirect('properties:sorry')
    userForm = UserForm(request.POST or None, instance=user)
    #infoForm = TenantInfoForm(request.POST or None, instance=info)
    infoForm = TenantInfoForm(request.POST or None)
    if userForm.is_valid() and infoForm.is_valid():
        userForm.save()
        #SinfoForm.save()
        user.set_password(userForm.cleaned_data['password'])
        user.save()
        return redirect('properties:user_list')
    return render(request, template_name, {'userForm':userForm, 'infoForm':infoForm, 'object':user})

def user_delete(request, pk, template_name='properties/user_confirm_delete.html'):
    if not request.user.is_authenticated():
        return redirect("/")
    if not request.user.is_superuser:
        return redirect('properties:sorry')
    user = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        user.delete()
        return redirect('properties:user_list')
    return render(request, template_name, {'object':user})
    
def no_delete(request, pk, template_name='properties/user_confirm_delete.html'):
    if not request.user.is_authenticated():
        return redirect("/")
    return redirect('properties:user_list')





### Property CRUD Functions ###

def add_manager(request, pk, template_name='properties/add_manager.html'):
    if not request.user.is_superuser:
        return redirect('properties:sorry')
    property = get_object_or_404(Property, pk=pk)
    form = AddManagerForm(request.POST or None)
    if form.is_valid():
        pg = PropertyGroup.objects.get(prop=property)
        mgr = form.cleaned_data['manager']
        mgr_id = User.objects.get(username=mgr).id
        pg.users.append(mgr_id)
        pg.save()
        return redirect('properties:property_list')
    return render(request, template_name, {'form':form})

def remove_manager(request, pk, mgr):
    if not request.user.is_authenticated():
        return redirect("/")
    if not request.user.is_superuser:
        return redirect('properties:sorry')
    property = get_object_or_404(Property, pk=pk)
    pg = PropertyGroup.objects.get(prop=property)
    pg.users = [x for x in pg.users if x != int(mgr)]
    pg.save()
    return redirect('properties:property_list')
    
def no_delete(request, pk, template_name='properties/user_confirm_delete.html'):
    if not request.user.is_authenticated():
        return redirect("/")
    return redirect('properties:user_list')

def property_list(request, template_name='properties/property_list.html'):
    if not request.user.is_authenticated():
        return redirect("/")
    if request.user in User.objects.filter(groups__name="Tenants"):
        return redirect("properties:sorry")
    if request.user.is_superuser:
        properties = Property.objects.all()
    else:
        prop_ids = []
        for pg in PropertyGroup.objects.all():
            if request.user.id in pg.users:
                prop_ids.append(pg.prop.id)
        properties = Property.objects.filter(id__in=prop_ids)
    data = {}
    data['prop_list'] = properties
    return render(request, template_name, data)
    
def report_list(request, template_name='properties/report_list.html'):
    if not request.user.is_authenticated():
        return redirect("/")
    if not request.user in User.objects.filter(groups__name="Managers") and not request.user.is_superuser:
        return redirect('properties:sorry')
    reports = Report.objects.all()
    data = {}
    data['report_list'] = reports
    return render(request, template_name, data)
    
def property_create(request, template_name='properties/property_form.html'):
    if not request.user.is_authenticated():
        return redirect("/")
    if not request.user.is_superuser:
        return redirect('properties:sorry')
    form = PropertyForm(request.POST or None)
    if form.is_valid():
        prop = form.save()
        propGroup = PropertyGroup.objects.create(prop_id=prop.id)
        propGroup.save();
        return redirect('properties:property_list')
    return render(request, template_name, {'form':form,'isNew':True})
    
def report_create(request, template_name='properties/report_form.html'):
    if not request.user.is_authenticated():
        return redirect("/")
    if not request.user in User.objects.filter(groups__name="Managers") and not request.user.is_superuser:
        return redirect('properties:sorry')
    if request.method != 'POST':
        form = ReportForm()
    else:
        form = ReportForm(request.POST, request.FILES)
    if form.is_valid():
        report = form.save()
        return redirect('properties:report_list')
    return render(request, template_name, {'form':form,'isNew':True})

def property_update(request, pk, template_name='properties/property_form.html'):
    if not request.user.is_authenticated():
        return redirect("/")

proManage/proManage/templates/properties/Report_list.html
{% load staticfiles %}
{% include "headers/standard.html" %}
<div id="contents">
	<div id="pagetitle">
		<h1>Reports</h1>
	</div>
	
	<table id="user-table">
		<thead>
			<tr>
				<th id="report-table-h1">Report</th>
				<th id="report-table-h2"> </th>
				<th id="report-table-h3"> </th>
			</tr>
		</thead>
		<tbody>
		
		{% for report in report_list %}
		<tr>
			<td>{{ report.fileDescription}}</td>
			<td><a href="{% static 'reports/'|add:report.fileBytes.url %}" download>Download</a></td>
			<td>
				<input type="button" onclick="window.location='{% url 'properties:report_delete' report.id %}';" value="Delete"/>
			</td>
		</tr>
		{% endfor %}
		</tbody>

	</table>

	<a href="{% url 'properties:report_new' %}">New Report</a>
</div>

proManage/proManage/templates/properties/add_manager.html
{% load staticfiles %}
{% include "headers/standard.html" %}
<div id="contents">
	<div id="pagetitle">
		<h1>Add Manager</h1>
	</div>
<form method="post">{% csrf_token %}
	<table id="manage-user-table">
		<tr>
			<td>Manager:</td><td>{{ form.manager }}</td><td>{{ form.manager.errors }}</td>
		</tr>
	</table>
    <input type="submit" value="Submit" />
	<input type="button" value="Cancel" onclick="window.location='{% url 'properties:property_list'%}';"/>
      

  
</form>
</div>

proManage/proManage/templates/properties/add_tenant.html
{% load staticfiles %}
{% include "headers/standard.html" %}
<div id="contents">
	<div id="pagetitle">
		<h1>Add Tenant</h1>
	</div>
<form method="post">{% csrf_token %}
	<table id="manage-user-table">
		<tr>
			<td>Tenant:</td><td>{{ form.tenant }}</td><td>{{ form.tenant.errors }}</td>
		</tr>
	</table>
    <input type="submit" value="Submit" />
	<input type="button" value="Cancel" onclick="window.location='{% url 'properties:property_list'%}';"/>
      

  
</form>
</div>

proManage/proManage/templates/properties/landing.html
{% load staticfiles %}
{% include "headers/standard.html" %}
<div id="contents">
	<table id="nav-table">
		<tr>
			<td class="nav-left"><input type="button" value="Users" onclick="window.location='{% url 'properties:user_list'%}';"/></td>
			<td class="nav-right"><input type="button" value="Properties" onclick="window.location='{% url 'properties:property_list'%}';" /> </td>
		</tr>
		<tr>
			<td class="nav-left"><input type="button" value="Work Orders" onclick="window.location='{% url 'properties:workorder_list' %}';" /> </td>
			<td class="nav-right"><input type="button" value="Reports" onclick="window.location='{% url 'properties:report_list' %}';"  /></td>
		</tr>
    <tr>
			<td class="nav-left"><input type="button" value="Send Text" onclick="window.location='{% url 'properties:sms_me' %}';"  /></td>
      <td></td>
    </tr>
	</table>
	
</div>

proManage/proManage/templates/properties/login.html
{% load staticfiles %}
{% include "headers/standard.html" %}
<div id="contents">
	<div id="pagetitle">
		<h1>Login</h1>
	</div>
	
	{% if form.errors %}
		<p>Your username and password didn't match</p>
	{% endif %}
<form method="post">{% csrf_token %}
	<table id="manage-user-table">
		<tr>
			<td>Username:</td><td>{{ form.username }}</td><td>{{ form.username.errors }}</td>
		</tr>
		<tr>
			<td>Password:</td><td>{{ form.password }}</td><td>{{ form.password.errors }}</td>
		</tr>
	</table>


    <input type="submit" value="Login" />
	<input type="hidden" name="next" value="{% url 'properties:landing'%}">
</form>
</div>

proManage/proManage/templates/properties/property_form.html
{% load staticfiles %}
{% include "headers/standard.html" %}
<div id="contents">
	<div id="pagetitle">
		<h1>Manage Property</h1>
	</div>
<form method="post">{% csrf_token %}
	<table id="manage-user-table">
		<tr>
			<td>Name:</td><td>{{ form.name }}</td><td>{{ form.name.errors }}</td>
		</tr>
		<tr>
			<td>Address:</td><td>{{ form.address }}</td><td>{{ form.address.errors }}</td>
		</tr>
		<tr>
			<td>City:</td><td>{{ form.city }}</td><td>{{ form.city.errors }}</td>
		</tr>
		<tr>
			<td>State:</td><td>{{ form.state }}</td><td>{{ form.state.errors }}</td>
		</tr>
		<tr>
			<td>Zipcode:</td><td>{{ form.zipcode }}</td><td>{{ form.zipcode.errors }}</td>
		</tr>
	</table>
    <input type="submit" value="Submit" />
	<input type="button" value="Cancel" onclick="window.location='{% url 'properties:property_list'%}';"/>
      
  {% if not isNew %}
  <input id="delete_button" type="button" value="Delete" onclick="window.location='{% url 'properties:property_delete' object.id%}';"/> 
  {% endif %}
    {% if not isNew %}
        <h2>Units</h2>
        <table id="header-set">
        <thead>
			<tr>
				<th class="unit-table-h1">Unit #</th>
				<th class="unit-table-h2">Type</th>
                <th class="unit-table-h3">Size</th>
				<th class="unit-table-h4"> </th>
                <th class="unit-table-h5"> </th>
			</tr>
		</thead>
    </table>
	<table id="user-table">
		<!--<thead>
			<tr>
				<th id="user-table-h1">Name</th>
				<th id="user-table-h2">Location</th>
				<th id="user-table-h3"> </th>
			</tr>
		</thead>-->
        <colgroup>
            <col class="unit-table-h1">
            <col class="unit-table-h2">
            <col class="unit-table-h3">
            <col class="unit-table-h4">
            <col class="unit-table-h5">
        </colgroup>
		<tbody>
		
		{% for unit in unit_info %}
		<tr>
			<td>{{ unit.unitNumber }}</td>
			<td>{{ unit.aptType }}</td>
            <td>{{ unit.size }}</td>
			<td id="unit-manage">
				<input type="button" onclick="window.location='{% url 'properties:unit_edit' unit.id %}';" value="Manage"/>
			</td>
            <td>
				<input type="button" onclick="window.location='{% url 'properties:unit_delete' unit.id %}';" value="Delete"/>
			</td>
		</tr>
		{% endfor %}
		</tbody>

	</table>

	<a href="{% url 'properties:unit_add' object.id %}">New Unit</a>
    {% endif %}

{% if not isNew %}
<h1>Managers</h1>
<u1>
    {% for manager in managers %}
        <li> {{ manager.first_name }} {{ manager.last_name }}</li>
    <a href="{% url 'properties:remove_manager' object.id manager.id %}">Remove Manager</a>
    {% endfor %}
    <br>
    <a href="{% url 'properties:add_manager' object.id %}">Add Manager</a>
</u1>
{% endif %}

  
</form>
</div>

proManage/proManage/templates/properties/property_list.html
{% load staticfiles %}
{% include "headers/standard.html" %}
<script src="{% static "js/propertiesList.js" %}"></script>
<div id="contents">
	<div id="pagetitle">
		<h1>Properties</h1>
	</div>
    
    <div id="filter-div">
        <label>Filter:</label><input type="text" id="filter" name="filter"/> 
    </div>
	
    <table id="header-set">
        <thead>
			<tr>
				<th class="user-table-h1">Name</th>
				<th class="user-table-h2">Location</th>
				<th class="user-table-h3"> </th>
			</tr>
		</thead>
    </table>
	<table id="user-table">
		<!--<thead>
			<tr>
				<th id="user-table-h1">Name</th>
				<th id="user-table-h2">Location</th>
				<th id="user-table-h3"> </th>
			</tr>
		</thead>-->
        <colgroup>
            <col class="user-table-h1">
            <col class="user-table-h2">
            <col class="user-table-h3">
        </colgroup>
		<tbody>
		
		{% for property in prop_list %}
		<tr>
			<td>{{ property.name }}</td>
			<td>{{ property.city }}, {{property.state}}</td>
			<td>
				<input type="button" onclick="window.location='{% url 'properties:property_edit' property.id %}';" value="Manage"/>
			</td>
		</tr>
		{% endfor %}
		</tbody>

	</table>

	<a href="{% url 'properties:property_new' %}">New Property</a>
</div>

proManage/proManage/templates/properties/report_confirm_delete.html
{% load staticfiles %}
{% include "headers/standard.html" %}
<div id="contents">
	<div id="pagetitle">
		<h1>Confirm Delete</h1>
	</div>
	<form method="post">{% csrf_token %}
		Are you sure you want to delete this report?
		<table>
			<tr>
				<td>Report: </td>
				<td>
					{{ object.fileDescription }}
				</td>
			</tr>
		</table>
		
		<input type="submit" value="Submit" />
	</form>
</div>

proManage/proManage/templates/properties/report_form.html
{% load staticfiles %}
{% include "headers/standard.html" %}
<div id="contents">
	<div id="pagetitle">
		<h1>Manage Report</h1>
	</div>
<form enctype="multipart/form-data" method="post">{% csrf_token %}
	<table id="manage-user-table">
		<tr>
			<td>File Description:</td><td>{{ form.fileDescription }}</td><td>{{ form.fileDescription.errors }}</td>
		</tr>
		<tr>
			<td>File:</td><td>{{ form.fileBytes }}</td><td>{{ form.fileBytes.errors }}</td>
		</tr>
	</table>


    <input type="submit" value="Submit" />
	<input type="button" value="Cancel" onclick="window.location='{% url 'properties:report_list'%}';"/>
  {% if not isNew %}
  <input id="delete_button" type="button" value="Delete" onclick="window.location='{% url 'properties:report_delete' object.id%}';"/> 
  {% endif %}
</form>

</div>

proManage/proManage/templates/properties/sms_me.html
{% load staticfiles %}
{% include "headers/standard.html" %}

<form method="post">{% csrf_token %}
        <table>
        <tr>
                <td>Text Message:</td>
                <td>{{ form.textdata }}</td>
        </tr>
</table>
    <input type="submit" value="Submit" />
	<input type="button" value="Cancel" onclick="window.location='{% url 'properties:landing'%}';"/>
 
  </form>

proManage/proManage/templates/properties/sorry.html
Sorry bro, you can't do this!

proManage/proManage/templates/properties/unit_form.html
{% load staticfiles %}
{% include "headers/standard.html" %}
<div id="contents">
	<div id="pagetitle">
		<h1>Manage Unit</h1>
	</div>
<form method="post">{% csrf_token %}
	<table id="manage-user-table">
    {% if isNew %}
		<tr>
			<td>Building:</td><td>{{ address }}</td>
		</tr>
        {% endif %}
		<tr>
			<td>Size:</td><td>{{ form.size }}</td><td>&nbspSqft{{ form.size.errors }}</td>
		</tr>
		<tr>
			<td>Unit Type:</td><td>{{ form.aptType }}</td><td>{{ form.aptType.errors }}</td>
		</tr>
		<tr>
			<td>Rental Fee:</td><td>${{ form.rentalFee }}</td><td>{{ form.rentalFee.errors }}</td>
		</tr>
		<tr>
			<td>Unit Number:</td><td>{{ form.unitNumber }}</td><td>{{form.unitNumber.errors }}</td>
		</tr>
	</table>


    <input type="submit" value="Submit" />
	<input type="button" value="Cancel" onclick="window.location='{% url 'properties:property_list'%}';"/>
  {% if not isNew %}
  <input id="delete_button" type="button" value="Delete" onclick="window.location='{% url 'properties:unit_delete' object.id%}';"/> 
  {% endif %}
</form>

  {% if not isNew %}
<h1>Tenants</h1>
    {% for tenant in tenants %}
    <li> {{ tenant.first_name }} {{ tenant.last_name }} </li>
<a href="{% url 'properties:remove_tenant' object.id tenant.id %}">Remove Tenant</a>  
  {% endfor %}
    <a href="{% url 'properties:add_tenant' object.id %}">Add Tenant</a>
  {% endif %}
</div>

proManage/proManage/templates/properties/unit_list.html
{% load staticfiles %}
{% include "headers/standard.html" %}
<div id="contents">
	<div id="pagetitle">
		<h1>Units</h1>
	</div>
		{% for unit in unit_list %}
		<li> {{ unit }}
		</li>
		<a href="{% url 'properties:unit_edit' unit.id %}">edit</a>
		<a href="{% url 'properties:unit_delete' unit.id %}">delete</a>
		<a href="{% url 'properties:unit_view_info' unit.id %}">view info</a>
		{% endfor %}


		<a href="{% url 'properties:unit_new' %}">New Unit</a>
</div>

proManage/proManage/templates/properties/user_list.html
{% load staticfiles %}
{% include "headers/standard.html" %}
<div id="contents">
	<div id="pagetitle">
		<h1>Users</h1>
	</div>
	
	<table id="user-table">
		<thead>
			<tr>
				<th id="user-table-h1">Full Name</th>
				<th id="user-table-h2">User Name</th>
				<th id="user-table-h3">Role(s)</th>
				<th id="user-table-h4"> </th>
			</tr>
		</thead>
		<tbody>
		
		{% for user in object_list %}
		<tr>
			<td>{{ user.first_name }} {{ user.last_name }}</td>
			<td>{{ user.username }}</td>
			<td>{% for group in user.groups.all %}
				    {{ group.name }} 
			    {% endfor %}</td>
			<td>
				<input type="button" onclick="window.location='{% url 'properties:user_edit' user.id %}';" value="Manage"/>
			</td>
		</tr>
		{% endfor %}
		</tbody>

	</table>

	<a href="{% url 'properties:user_new' %}">New User</a>
</div>